# Generated by Django 3.2.1 on 2021-05-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100, verbose_name='Токен')),
                ('bot_is_on', models.BooleanField(verbose_name='Бот включен')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100, unique=True, verbose_name='Имя элемента')),
                ('element_text', models.TextField(verbose_name='Текст элемента')),
            ],
        ),
        migrations.CreateModel(
            name='ElementAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Имя ветки')),
                ('element_name', models.CharField(max_length=100, verbose_name='Имя элемента')),
                ('addition_text', models.CharField(max_length=100, verbose_name='Текст дополнения')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.element')),
            ],
        ),
        migrations.CreateModel(
            name='ElementTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Имя ветки')),
                ('element_name', models.CharField(max_length=100, verbose_name='Имя элемента')),
                ('transition_text', models.CharField(max_length=100, verbose_name='Текст перехода')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.element')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100, unique=True, verbose_name='Имя ветки')),
                ('element_number', models.IntegerField(verbose_name='Количество элементов ветки')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('scheme_name', models.CharField(max_length=100, verbose_name='Имя ветки')),
                ('element_name', models.CharField(max_length=100, verbose_name='Имя элемента')),
            ],
        ),
        migrations.DeleteModel(
            name='BotAdmin',
        ),
        migrations.AddField(
            model_name='element',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.scheme'),
        ),
    ]
