# Generated by Django 3.2.1 on 2021-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210516_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementaddition',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='elementaddition',
            name='element_name',
        ),
        migrations.RemoveField(
            model_name='elementtransition',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='elementtransition',
            name='element_name',
        ),
        migrations.AddField(
            model_name='elementaddition',
            name='addition_element',
            field=models.CharField(default=None, max_length=100, verbose_name='Элемент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementtransition',
            name='transition_element',
            field=models.CharField(default='', max_length=100, verbose_name='Элемент'),
            preserve_default=False,
        ),
    ]
