# Generated by Django 3.2.1 on 2021-05-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210516_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='element_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scheme_name',
        ),
        migrations.AddField(
            model_name='user',
            name='element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.element'),
            preserve_default=False,
        ),
    ]
