# Generated by Django 3.2.1 on 2021-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_user_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bot_type',
            field=models.CharField(default='', max_length=100, verbose_name='Социальная сеть'),
            preserve_default=False,
        ),
    ]
