# Generated by Django 3.2.1 on 2021-05-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_config_bot_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='elementaddition',
            options={'verbose_name': 'Дополнение', 'verbose_name_plural': 'Дополнения'},
        ),
        migrations.AlterModelOptions(
            name='elementtransition',
            options={'verbose_name': 'Переход', 'verbose_name_plural': 'Переходы'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='messenger_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя соц-сети'),
            preserve_default=False,
        ),
    ]
