# Generated by Django 3.2.1 on 2021-05-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210518_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя мессенджера')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
        migrations.RenameField(
            model_name='config',
            old_name='bot_is_on',
            new_name='is_on',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='elementaddition',
            old_name='addition_element',
            new_name='addition',
        ),
        migrations.RenameField(
            model_name='elementaddition',
            old_name='addition_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='elementtransition',
            old_name='transition_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='elementtransition',
            old_name='transition_element',
            new_name='transition',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='scheme_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='bot_token',
        ),
        migrations.RemoveField(
            model_name='config',
            name='bot_type',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='element_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='messenger_name',
        ),
        migrations.AddField(
            model_name='config',
            name='token',
            field=models.CharField(max_length=100, null=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='config',
            name='messenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='messenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
            preserve_default=False,
        ),
    ]
