# Generated by Django 3.2.1 on 2021-05-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210518_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='messenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
        ),
        migrations.AlterField(
            model_name='user',
            name='messenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
        ),
    ]
