# Generated by Django 3.2.1 on 2021-05-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210518_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.scheme'),
        ),
        migrations.AlterField(
            model_name='elementaddition',
            name='addition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addition_to', to='manager.element'),
        ),
        migrations.AlterField(
            model_name='elementaddition',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addition_from', to='manager.element'),
        ),
        migrations.AlterField(
            model_name='elementtransition',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_from', to='manager.element'),
        ),
        migrations.AlterField(
            model_name='elementtransition',
            name='transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_to', to='manager.element'),
        ),
    ]
