# Generated by Django 3.2.1 on 2021-05-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210518_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='messenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='scheme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.scheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementaddition',
            name='addition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addition_to', to='manager.element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementaddition',
            name='element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addition_from', to='manager.element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementtransition',
            name='element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transition_from', to='manager.element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementtransition',
            name='transition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transition_to', to='manager.element'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='messenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.messenger'),
            preserve_default=False,
        ),
    ]
