# Generated by Django 3.2.1 on 2021-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20210519_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': '2. Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': '5. Элементы'},
        ),
        migrations.AlterModelOptions(
            name='elementaddition',
            options={'verbose_name': 'Дополнение', 'verbose_name_plural': '6. Дополнения'},
        ),
        migrations.AlterModelOptions(
            name='elementtransition',
            options={'verbose_name': 'Переход', 'verbose_name_plural': '7. Переходы'},
        ),
        migrations.AlterModelOptions(
            name='messenger',
            options={'verbose_name': 'Мессенджер', 'verbose_name_plural': '1. Мессенджеры'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Схема', 'verbose_name_plural': '4. Схемы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '3. Пользователи'},
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя элемента'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя схемы'),
        ),
    ]
