# Generated by Django 3.2.1 on 2021-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20210522_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_update', models.BooleanField(verbose_name='Требуется обновление файла XML')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': '0. Обновление',
            },
        ),
    ]
