# Generated by Django 3.2.1 on 2021-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_xmlupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя элемента'),
        ),
    ]
