# Generated by Django 3.2.1 on 2021-05-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_element_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.element'),
        ),
    ]
